name: Run LinkedIn Playwright Script

on:
  workflow_dispatch:  # allows manual trigger via GitHub UI

jobs:
  run-playwright-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Playwright Script
        run: node linkedin.js

